name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        cd server && gradle clean package
        gradle publish
        echo -e $BASE_REF
    env: 
      BASE_REF: ${{ github.base_ref }}
